--- 
- Delicious
- Reddit
- Digg
- NewsVine
- Delirious
- Blinkbits
- BlinkList
- Blogmarks
- Comments
- Fark
- Furl
- Magnolia
- Netvouz
- Scuttle
- Shadows
- Simpy
- TailRank
- YahooMyWeb
